
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - s-network
  postgres:
    image: postgres
    environment:
      POSTGRES_USER : Swathi
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Docker
    ports:
      - "5432:5432"
    networks:
      - s-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  s-network:
    driver: bridge

volumes:
  postgres-s-data:
